resources:
 - name: myAppRepo
   type: GitRepo
   configuration:
     gitProvider: GitHubAcc
     path: anupteal/micro-service
     branches:
        include: javacode		

pipelines:
 - name: pipeline_hello_world
   configuration:
      environmentVariables:
         readOnly:
            MY_MESSAGE: "Hello Anup"
   steps:
     - name: step1
       type: Bash
       configuration:
          inputResources:
            - name: myAppRepo
       execution:
         onExecute:
            - echo $MY_MESSAGE
            - echo "Running $pipeline_name | $step_name on node ID $step_node_id"
            - pwd && ls -lrth workspace && find / -iname "pom.xml" 
            - javac -version
            - mvn --version  
     - name: compilation
       type: MvnBuild
       configuration:
           sourceLocation: department-service
           mvnCommand: clean install
           configFileLocation: department-service/src/main/resources 
           configFileName: application.yml
           inputResources:
             - name: myAppRepo  
           integrations:
             - name: myArtifactory 
       execution:
            onStart:
              - javac -version
              - mvn  --version
